JBOFarmersMkt/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JBOFarmersMkt.Context;
using JBOFarmersMkt.Models;
using PagedList;
using PagedList.Mvc;

namespace JBOFarmersMkt.Controllers
{
    public class SaleController : Controller
    {
        private JBOContext db = new JBOContext();

        //
        // GET: /Sale/
        [Authorize]
        public ActionResult Index(int? page, string sortBy, int? search, string searchName, string searchSupplier)
        {
            if (User.Identity.Name != "admin")
            {
                ///<summary>
                ///
                /// lambda expression to select the user object that is logged in.    
                /// 
                ///</summary>
                ///<remarks>
                /// None
                ///</remarks>
                ///

                UserProfile user = db.UserProfiles.FirstOrDefault(u => u.UserName == User.Identity.Name);

                ///<summary>
                ///
                /// linq statement to build a list of all suppliers that have the logged in user
                /// in the user ICollection of the suppliers.  If the UserProfile user is not null 
                /// then execute the linq query statments, else return a blank view.  If the       
                /// logged in user is not "admin" then linq will pull all of the sale items        
                /// associated with the corresponding supplier, else linq will pull all sales for  
                /// the user "admin".
                /// 
                ///</summary>
                ///<remarks>
                /// None
                ///</remarks>

                if (user != null)
                {
                    var supplier = (from s in db.Suppliers
                                    where s.users.Any(i => i.UserId == user.UserId)
                                    select s.name).ToList();

                    var sale = from s in db.Sales
                                  where supplier.Contains(s.supplier)
                                  select s;


                    ///<summary>
                    ///
                    /// sale is passed to salesQuery as a Queryable object 
                    /// 
                    ///</summary>
                    ///<remarks>
                    /// None
                    ///</remarks>
                    ///

                    var saleQuery = sale.AsQueryable();

                    ///<summary>
                    ///
                    /// Sort Parameters and query string patterns for Date, Supplier, and 
                    /// Description along with Switch control to determine what sort pattern to 
                    /// follow by.
                    /// 
                    ///</summary>
                    ///<remarks>
                    /// None
                    ///</remarks>
                    ///

                    ViewBag.SortCodeParameter = string.IsNullOrEmpty(sortBy) ? "transCode desc" : "";
                    ViewBag.SortSupplierParameter = string.IsNullOrEmpty(sortBy) ? "supplier desc" : "";
                    ViewBag.SortItemParameter = string.IsNullOrEmpty(sortBy) ? "description desc" : "";

                    switch (sortBy)
                    {

                        case "transCode desc": //order by supplier descending
                            saleQuery = saleQuery.OrderByDescending(x => x.transCode);
                            break;

                        case "description desc": //order by description descending
                            saleQuery = saleQuery.OrderByDescending(x => x.description);
                            break;

                        case "description": //order by description ascending
                            saleQuery = saleQuery.OrderBy(x => x.description);
                            break;

                        default: //default order by supplier ascending
                            saleQuery = saleQuery.OrderBy(x => x.supplier);
                            break;
                    }


                    ///<summary>
                    ///
                    /// If search is not null then return the sale items requested.
                    /// 
                    ///</summary>
                    ///<remarks>
                    /// None
                    ///</remarks>
                    ///  

                    if (search != null && saleQuery != null)
                    {

                        return View(sale.Where(x => x.transCode == search).ToList().ToPagedList(page ?? 1, 10));

                    }

                    if (searchName != null)
                    {

                        return View(sale.Where(p => p.description.ToUpper().Contains(searchName.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
                    }

                    if (saleQuery != null)
                    {
                        return View(saleQuery.ToList().ToPagedList(page ?? 1, 20));
                    }

                }
            }
            else
            {
                ///<summary>
                ///
                /// Calculate Total Sales.  Uses linq expression to total the sales.  Then passes  
                /// the total figure to the view.
                /// 
                ///</summary>
                ///<remarks>
                /// None
                ///</remarks>
                ///  

                var retrieve = from s in db.Sales select s;
                if (retrieve.Any())
                {

                }
                else
                {
                    ViewBag.Message = "There are no sale items to display!";
                }

                var sales = from s in db.Sales select s;
                var saleQuery = sales.AsQueryable();

                ///<summary>
                ///
                /// Sort Parameters and query string patterns for Date, Supplier, and 
                /// Description along with Switch control to determine what sort pattern to 
                /// follow by.
                /// 
                ///</summary>
                ///<remarks>
                /// None
                ///</remarks>
                ///

                ViewBag.SortDateParameter = string.IsNullOrEmpty(sortBy) ? "date desc" : "";
                ViewBag.SortSupplierParameter = string.IsNullOrEmpty(sortBy) ? "supplier desc" : "";
                ViewBag.SortItemParameter = string.IsNullOrEmpty(sortBy) ? "description desc" : "";

                switch (sortBy)
                {

                    case "supplier desc": //order by supplier descending
                        saleQuery = saleQuery.OrderByDescending(x => x.supplier);
                        break;

                    case "supplier": //order by supplier ascending
                        saleQuery = saleQuery.OrderBy(x => x.supplier);
                        break;

                    case "description desc": //order by description descending
                        saleQuery = saleQuery.OrderByDescending(x => x.description);
                        break;

                    case "description": //order by description ascending
                        saleQuery = saleQuery.OrderBy(x => x.description);
                        break;

                    default: //default order by supplier ascending
                        saleQuery = saleQuery.OrderBy(x => x.supplier);
                        break;
                }


                ///<summary>
                ///
                /// If search is not null then return the items requested. 
                /// 
                /// 
                ///</summary>
                ///<remarks>
                /// None
                ///</remarks>
                ///  
                if (search != null && saleQuery != null)
                {
                    return View(db.Sales.Where(x => x.transCode == search).ToList().ToPagedList(page ?? 1, 10));
                }

                if (searchName != null)
                {
                    return View(db.Sales.Where(p => p.description.ToUpper().Contains(searchName.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
                }

                if (searchSupplier != null)
                {
                    return View(db.Sales.Where(p => p.supplier.ToUpper().Contains(searchSupplier.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
                }

                else
                {
                    return View(saleQuery.ToList().ToPagedList(page ?? 1, 20));
                }


            }

            ///<summary>
            ///
            /// If all above fails, then return a blank view.
            /// 
            ///</summary>
            ///<remarks>
            /// None
            ///</remarks>
            ///  

            return View();

        }

        //
        // GET: /Sale/Details/5

        public ActionResult Details(int id = 0)
        {
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        //
        // GET: /Sale/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Sale/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sale);
        }

        //
        // GET: /Sale/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {

JBOFarmersMkt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <style>
            #nav ul {
                display: none;
            }

            #nav li:hover > ul {
                display: block;
            }
        </style>

    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Jonesborough Farmers Market", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Store", "Index", "Store")</li>
                            <li>@Html.ActionLink("Sales", "Index", "Sale")</li>
                            @if(User.Identity.Name == "admin")
                            { 
                                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>                             
                                <li>@Html.ActionLink("Suppliers", "Index", "Supplier")</li>
                            }
                            <li>@Html.ActionLink("Products", "Index", "Product")</li>
                            <li>@Html.ActionLink("Returns", "Index", "Return")</li>                            
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            @if(User.Identity.Name == "admin")
                            { 
                                <li>@Html.ActionLink("Import", "importProducts", "Import")</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - 2Venture Enterprises, Inc</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>